### ISSUE TITLE
taskview activity goes through old versions of activity instead of immediatley going through main

### ISSUE THREAD

**Issue by jejewittt** [CMPUT301W18T23/GeoTask#25]
ie if you are a taskrequester and you accept - then delete the task, accpet then delete the task  ....
the old statuses will show if you try to go back with the back button 

I have a fix for this, but it may break unit testing / ui testing so im not going to implement it right now:
this is the change

(going directly to the acttivty instead of calling it) 

```
    @Override
    public void onBackPressed() {
        Intent intent = new Intent(getBaseContext(), MenuActivity.class);
        intent.putExtra(getString(R.string.CURRENT_USER), currentUser);
        startActivity(intent);
    }
```

**Comment by FlamingLobster** [comment]
this is the same problem we had with the login page isn't it? the onBackPress() isn't overridden

**Comment by FlamingLobster** [comment]
or is this because there are two instances of view task

**Comment by jejewittt** [comment]
i think its because there are 2 instances of viewtask.

**Comment by TannerShmoog** [comment]
This was implemented a while ago to fix a memory leak
```
@Override
    public void onBackPressed() {
        MenuActivity.setLastClicked(getCurrentTask());
        Intent intent = new Intent(getBaseContext(), MenuActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        startActivity(intent);
    }
```
