### ISSUE TITLE
When to add a bid

### ISSUE THREAD

**Issue by lepoidev** [CMPUT301W18T23/GeoTask#38]
Right now a user adds a bid while they are viewing the task. If a real user were using the app, they would probably look at the other bids before/while they make their own bid. I can think of 3 solutions:
1 - display the lowest bid while the user is adding a bid or somewhere else in the activity
2 - move the add bid button to the bid list view
3 - move the bid list to the task view as per #29 
We should talk more about this tomorrow

**Comment by FlamingLobster** [comment]
I like 2 more than 3. Suppose the we add description to Bid, then the display that only spans half the screen is too small.

**Comment by lepoidev** [comment]
old button is hidden, new button is on ViewBidsActivity
