### ISSUE TITLE
User should not be able to edit bid when offline

### ISSUE THREAD

**Issue by FlamingLobster** [CMPUT301W18T23/GeoTask#44]

**Comment by FlamingLobster** [comment]
can add bids

**Comment by FlamingLobster** [comment]
can add

**Comment by FlamingLobster** [comment]
allowing deleting bloats the logic too much, easier to just not allow deleting

**Comment by FlamingLobster** [comment]
can we also not allow accepting bids when offline, also bloats logic too much

**Comment by FlamingLobster** [comment]
Basically the only things allowed when offline are editing task and adding bid

**Comment by TannerShmoog** [comment]
Everything relevant has been disallowed
