### ISSUE TITLE
MenuActivity Change Mode Lag

### ISSUE THREAD

**Issue by FlamingLobster** [CMPUT301W18T23/GeoTask#9]
Calling search inside TaskArrayAdapter halts the UI cause long pause when changing mode.

**Comment by lepoidev** [comment]
we could save the lowest bid in the task class and store it in the server. It would be a bit tedious making sure its up to date when someone deletes a bid or updates a bid but it would definitely get rid of the lag

**Comment by jejewittt** [comment]
on my phone there is little to no lag so maybe this is an emulator thing?

**Comment by TannerShmoog** [comment]
fixed with offline database
